### ISSUE TITLE
Docker: Flower not installed in docker build

### ISSUE THREAD

**Issue by certrik** [opensemanticsearch/open-semantic-search#323]
After running `docker-compose up` it is not possible to review ETL Tasks because flower isn't installed or running.

**Comment by NetwarSystem** [comment]
Troubles with flower have been ongoing. I am not up on the Docker aspect of running OSS, for my system I manually installed flower, and then created a flower.service file for systemd to run it. Note that you might also need to adjust the location of flower in the OSS setup tab - it defaults to localhost:5555.


[Unit]
Description=Flower Server
After=network.target

[Service]
Type=simple
User=tika
ExecStart=/usr/local/bin/flower --address=0.0.0.0
Restart=always

[Install]
WantedBy=multi-user.target

**Comment by phretor** [comment]
Just add this after the `rabbitmq:` service entry in `docker-compose.yml`:

```
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
```

and

```
$ docker-compose up -d
```
